import React, { createContext, useContext, useState, useCallback } from 'react';

type Lang = 'fr' | 'ar';

const translations = {
  fr: {
    appName: 'FacturaPro Maroc',
    tagline: 'Facturation conforme 2026',
    dashboard: 'Tableau de bord',
    invoices: 'Factures',
    clients: 'Clients',
    products: 'Produits',
    reports: 'Rapports',
    createInvoice: 'Nouvelle facture',
    totalRevenue: 'Chiffre d\'affaires',
    pendingInvoices: 'Factures en attente',
    recentClients: 'Clients récents',
    validated: 'Validées',
    thisMonth: 'Ce mois',
    invoiceNumber: 'N° Facture',
    client: 'Client',
    date: 'Date',
    totalTTC: 'Total TTC',
    totalHT: 'Total HT',
    status: 'Statut',
    actions: 'Actions',
    pending: 'En attente',
    paid: 'Payée',
    cancelled: 'Annulée',
    draft: 'Brouillon',
    businessName: 'Raison sociale',
    ice: 'ICE (15 chiffres)',
    ifField: 'Identifiant Fiscal (IF)',
    address: 'Adresse',
    description: 'Désignation',
    quantity: 'Qté',
    unitPrice: 'P.U HT',
    vatRate: 'TVA',
    lineTotal: 'Total HT',
    addLine: 'Ajouter une ligne',
    subtotalHT: 'Total HT',
    totalVAT: 'Total TVA',
    save: 'Enregistrer',
    validate: 'Valider',
    print: 'Imprimer',
    export: 'Exporter PDF',
    invoiceInfo: 'Informations facture',
    clientInfo: 'Informations client',
    invoiceLines: 'Lignes de facture',
    summary: 'Récapitulatif',
    amountWords: 'Arrêté la présente facture à la somme de',
    vatBreakdown: 'Détail TVA',
    qrCode: 'QR Code e-Facture',
    history: 'Historique',
    createAvoir: 'Créer un avoir',
    lockedInvoice: 'Facture validée – non modifiable',
    dueDate: 'Date d\'échéance',
    paymentMethod: 'Mode de paiement',
    notes: 'Notes',
    sellerInfo: 'Émetteur',
    cancel: 'Annuler',
    delete: 'Supprimer',
    noInvoices: 'Aucune facture',
    search: 'Rechercher...',
    revenueChart: 'Évolution du CA',
    invoiceStatus: 'Statut des factures',
    quickActions: 'Actions rapides',
    newClient: 'Nouveau client',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    welcome: 'Bonjour',
    companyName: 'Votre société',
    having: 'avoir',
    markAsPaid: 'Marquer comme payée',
    paidSuccess: 'Facture marquée comme payée ✓',
    validateSuccess: 'Facture validée avec succès',
    validateNumber: 'Numéro attribué',
    confirmValidate: 'Voulez-vous valider cette facture ? Elle ne pourra plus être modifiée.',
    confirmAvoir: 'Créer un avoir pour cette facture ? Cette action est irréversible.',
    confirmPaid: 'Marquer cette facture comme payée ?',
    filterDateFrom: 'Du',
    filterDateTo: 'Au',
    allClients: 'Tous les clients',
    noResults: 'Aucun résultat',
    invoicesOf: 'facture(s)',
    totalFiltered: 'Total filtré',
    // Reports
    reportsSubtitle: 'Récapitulatif TVA pour votre comptable',
    exportCSV: 'Exporter CSV',
    totalVATLabel: 'TVA collectée',
    vatToPay: 'À reverser à la DGI',
    vatBreakdownSub: 'Factures validées et payées uniquement',
    vatEvolution: 'Évolution de la TVA',
    vatEvolutionSub: 'Base HT et TVA collectée par période',
    monthly: 'Mensuel',
    quarterly: 'Trimestriel',
    total: 'Total',
    // Confirmation modals
    confirmValidateTitle: 'Valider la facture ?',
    confirmValidateDesc: 'Une fois validée, cette facture ne pourra plus être modifiée. Un numéro définitif lui sera attribué.',
    confirmAvoirTitle: 'Créer un avoir ?',
    confirmAvoirDesc: 'Un avoir (note de crédit) sera créé pour annuler cette facture. Cette action est irréversible.',
    confirmPaidTitle: 'Marquer comme payée ?',
    confirmPaidDesc: 'La facture passera au statut "Payée". Confirmez-vous le règlement ?',
    confirmCta: 'Confirmer',
    // New modules
    devis: 'Devis',
    bonCommande: 'Bon de Commande',
    bonLivraison: 'Bon de Livraison',
    achats: 'Achats & E-Facture',
    clientBalance: 'Solde client',
    totalBilled: 'Total facturé',
    totalPaid: 'Total payé',
    balanceDue: 'Solde dû',
    // Dashboard extras
    overdueInvoices: 'Factures en retard',
    totalClients: 'Total clients',
    pendingQuotes: 'Devis en attente',
    quotesNotConverted: 'Devis non encore convertis',
    uninvoicedBL: 'BL non facturés',
    deliveriesNoInvoice: 'Livraisons sans facture',
    lowStock: 'Stock faible',
    lowStockProducts: 'produit(s)',
    recentInvoicesTitle: 'Factures récentes',
    viewAll: 'Voir tout →',
    secureSystem: 'Système Sécurisé (Art. 210 CGI)',
    integrityCompromised: 'Intégrité compromise',
    last6Months: '6 derniers mois',
    // Sidebar
    commercialDocs: 'Documents commerciaux',
    eFactureDGI: 'E-Facture DGI 2026',
    clientStatement: 'État des Comptes',
    accounting: 'Comptabilité',
  },
  ar: {
    appName: 'فاكتورا برو المغرب',
    tagline: 'فوترة متوافقة 2026',
    dashboard: 'لوحة التحكم',
    invoices: 'الفواتير',
    clients: 'العملاء',
    products: 'المنتجات',
    reports: 'التقارير',
    createInvoice: 'فاتورة جديدة',
    totalRevenue: 'رقم المعاملات',
    pendingInvoices: 'فواتير معلقة',
    recentClients: 'أحدث العملاء',
    validated: 'مصادق عليها',
    thisMonth: 'هذا الشهر',
    invoiceNumber: 'رقم الفاتورة',
    client: 'العميل',
    date: 'التاريخ',
    totalTTC: 'المجموع شامل الضريبة',
    totalHT: 'المجموع بدون ضريبة',
    status: 'الحالة',
    actions: 'إجراءات',
    pending: 'معلقة',
    paid: 'مدفوعة',
    cancelled: 'ملغاة',
    draft: 'مسودة',
    businessName: 'اسم الشركة',
    ice: 'ICE (15 رقمًا)',
    ifField: 'المعرف الضريبي (IF)',
    address: 'العنوان',
    description: 'البيان',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    vatRate: 'ضريبة القيمة المضافة',
    lineTotal: 'المجموع',
    addLine: 'إضافة سطر',
    subtotalHT: 'المجموع قبل الضريبة',
    totalVAT: 'مجموع الضريبة',
    save: 'حفظ',
    validate: 'تصديق',
    print: 'طباعة',
    export: 'تصدير PDF',
    invoiceInfo: 'معلومات الفاتورة',
    clientInfo: 'معلومات العميل',
    invoiceLines: 'بنود الفاتورة',
    summary: 'الملخص',
    amountWords: 'حُررت هذه الفاتورة بمبلغ',
    vatBreakdown: 'تفاصيل الضريبة',
    qrCode: 'رمز QR للفاتورة',
    history: 'السجل',
    createAvoir: 'إنشاء إشعار دائن',
    lockedInvoice: 'فاتورة مصادق عليها – غير قابلة للتعديل',
    dueDate: 'تاريخ الاستحقاق',
    paymentMethod: 'طريقة الدفع',
    notes: 'ملاحظات',
    sellerInfo: 'معلومات البائع',
    cancel: 'إلغاء',
    delete: 'حذف',
    noInvoices: 'لا توجد فواتير',
    search: 'بحث...',
    revenueChart: 'تطور رقم المعاملات',
    invoiceStatus: 'حالة الفواتير',
    quickActions: 'إجراءات سريعة',
    newClient: 'عميل جديد',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً',
    companyName: 'شركتك',
    having: 'إشعار دائن',
    markAsPaid: 'تحديد كمدفوعة',
    paidSuccess: 'تم تحديد الفاتورة كمدفوعة ✓',
    validateSuccess: 'تم التصديق على الفاتورة بنجاح',
    validateNumber: 'الرقم المُسند',
    confirmValidate: 'هل تريد تصديق هذه الفاتورة؟ لن يمكن تعديلها بعد ذلك.',
    confirmAvoir: 'إنشاء إشعار دائن لهذه الفاتورة؟ هذا الإجراء لا رجعة فيه.',
    confirmPaid: 'تحديد هذه الفاتورة كمدفوعة؟',
    filterDateFrom: 'من',
    filterDateTo: 'إلى',
    allClients: 'جميع العملاء',
    noResults: 'لا توجد نتائج',
    invoicesOf: 'فاتورة',
    totalFiltered: 'المجموع المصفى',
    // Reports
    reportsSubtitle: 'ملخص الضريبة على القيمة المضافة لمحاسبك',
    exportCSV: 'تصدير CSV',
    totalVATLabel: 'الضريبة المحصلة',
    vatToPay: 'للتسديد لمصلحة الضرائب',
    vatBreakdownSub: 'الفواتير المصادق عليها والمدفوعة فقط',
    vatEvolution: 'تطور الضريبة على القيمة المضافة',
    vatEvolutionSub: 'الأساس بدون ضريبة والضريبة المحصلة حسب الفترة',
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    total: 'المجموع',
    // Confirmation modals
    confirmValidateTitle: 'تصديق الفاتورة؟',
    confirmValidateDesc: 'بمجرد التصديق، لن يمكن تعديل هذه الفاتورة. سيُسند لها رقم نهائي.',
    confirmAvoirTitle: 'إنشاء إشعار دائن؟',
    confirmAvoirDesc: 'سيتم إنشاء إشعار دائن لإلغاء هذه الفاتورة. هذا الإجراء لا رجعة فيه.',
    confirmPaidTitle: 'تحديد كمدفوعة؟',
    confirmPaidDesc: 'ستنتقل الفاتورة إلى حالة "مدفوعة". هل تؤكد الاستلام؟',
    confirmCta: 'تأكيد',
    // New modules
    devis: 'عروض الأسعار',
    bonCommande: 'أوامر الشراء',
    bonLivraison: 'وثائق التسليم',
    achats: 'المشتريات والفاتورة الإلكترونية',
    clientBalance: 'رصيد العميل',
    totalBilled: 'إجمالي المفوتر',
    totalPaid: 'إجمالي المدفوع',
    balanceDue: 'المبلغ المستحق',
    // Dashboard extras
    overdueInvoices: 'فواتير متأخرة',
    totalClients: 'إجمالي العملاء',
    pendingQuotes: 'عروض أسعار معلقة',
    quotesNotConverted: 'عروض أسعار لم تُحوّل بعد',
    uninvoicedBL: 'وثائق تسليم بدون فاتورة',
    deliveriesNoInvoice: 'تسليمات بدون فاتورة',
    lowStock: 'مخزون منخفض',
    lowStockProducts: 'منتج(ات)',
    recentInvoicesTitle: 'الفواتير الأخيرة',
    viewAll: '← عرض الكل',
    secureSystem: 'نظام آمن (المادة 210 م.ض.ع)',
    integrityCompromised: 'سلامة البيانات مخترقة',
    last6Months: 'آخر 6 أشهر',
    // Sidebar
    commercialDocs: 'الوثائق التجارية',
    eFactureDGI: 'الفاتورة الإلكترونية 2026',
    clientStatement: 'كشف الحسابات',
    accounting: 'المحاسبة',
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof translations.fr;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr');

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = l;
  }, []);

  const value: LanguageContextType = {
    lang,
    setLang,
    t: translations[lang],
    dir: lang === 'ar' ? 'rtl' : 'ltr',
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
}
